### ISSUE TITLE
logback configuration file with root debug level logging

### ISSUE THREAD

**Issue by darrenr** [ashwanthkumar/gocd-java-client#1]
I noticed that this jar bundles with logback configuration with root level debug logging enabled. If jar is used and appears first in the classpath for an application that has no logging defined it will switch debug on globally.  You may want to remove the config or maybe not set a more sensible default.

Of course this is a simple fix for clients (just configure logging) but I thought I'd point this out as it caught me out when I included your jar in a basic SpringBoot application.

**Comment by ashwanthkumar** [comment]
Thanks for reporting. This is now fixed as part of v0.0.4 version.
